### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Edelstadt** [honzajavorek/czech-holidays#8]
Maybe unit tests? Minimal for Good Friday. Or performance tests?

**Comment by honzajavorek** [comment]
I agree with unit tests, at least to check the interface. I'm willing to accept any contributions using pytest and to integrate the repo with Travis CI.

**Comment by honzajavorek** [comment]
I've added some tests today. Anyone is welcome to add more!

![image](https://user-images.githubusercontent.com/283441/187214420-240d473f-4446-4db1-9021-cf59d3cf1420.png)
